ems_serio: remove unused conflicing tios definition
Fixes the followng linker error:
  ems_serio/serial.c:10: multiple definition of `tios'; [...] ems_serio/ems_serio.c:27: first defined here